### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [asingh1969/tc359-project10#1]
This is looking mostly very good. Just a few updates I'd like you to make:
### Indentation

I see some hard-tabs throughout the project. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.
### Validation tweaks

An issue with the `:title` validation is that it doesn't allow punctuation, such as `'` or `!`, which are included in some movie titles. You can find out how to target punctuation in Ruby regex by searching for `ruby regex punctuation`. Also, this is purely a style issue, but the `$` isn't actually doing anything in this case, so it can be removed.

I would also include a custom message with the rating validation. When I try to enter `999` or another out of range number, I get a message simply saying: `Rating is not included in the list`, which isn't very helpful, since I don't know what the list is as a user.

**Comment by asingh1969** [comment]
Edited the indentation and validation.

**Comment by chrisvfritz** [comment]
Looks good, except `\W` actually matches _any_ non-word character. What you probably want instead is [described here](http://stackoverflow.com/questions/11130490/why-does-ruby-punct-miss-some-punctuation-characters). Let me know when that's updated or if you have any questions.

**Comment by asingh1969** [comment]
I changed it to use \p{Punct} now

**Comment by chrisvfritz** [comment]
:+1: Nice!
